In [1]:
import pandas as pd
import numpy as np


In [2]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_excel('../Data/pData.xlsx')

In [4]:
# list(df)

In [5]:
cat_columns = [
 'Industry_Chain_Position',
 'Level1_Technology_Branch',
 'Patent_Type',
 'Province_Code',
 'Patent_Validity',
]

In [6]:
ohEncoder = OneHotEncoder(drop='first')
cat_features = ohEncoder.fit_transform(df[cat_columns]).toarray()
cat_features

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 1.]])

In [7]:
num_columns = [ 
 'Number_Of_Citations_In_3',
 'Number_Of_Citations_In_5',
 'Number_Of_Citing_Patents',
 'Number_Of_Cited_Patents',
 'date',
 'Number_Of_Claims',
 'Literature_Pages',
 'Number_Of_Litigation_Cases'
]

In [8]:
stdScaler = StandardScaler()
num_features = stdScaler.fit_transform(df[num_columns])
num_features

array([[-0.35400295, -0.35393359, -0.45886953, ...,  0.06827662,
         1.21783217, -0.01844967],
       [-0.35400295, -0.35393359, -0.45886953, ..., -0.94696456,
        -0.55161798, -0.01844967],
       [-0.35400295, -0.35393359, -0.45886953, ..., -0.60855083,
        -0.99398052, -0.01844967],
       ...,
       [-0.35400295, -0.35393359, -0.45886953, ...,  0.40669034,
        -0.55161798, -0.01844967],
       [-0.35400295, -0.35393359, -0.45886953, ..., -0.27013711,
        -0.10925544, -0.01844967],
       [-0.35400295, -0.35393359, -0.12527161, ..., -0.27013711,
        -0.33043671, -0.01844967]])

In [9]:
X = np.hstack([cat_features, num_features])
X.shape

(73054, 58)

In [10]:
y = df['Patent_Value'].to_numpy()
y.shape

(73054,)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2)


In [12]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((58443, 58), (14611, 58), (58443,), (14611,))

In [13]:
from sklearn.linear_model import LinearRegression
LR =  LinearRegression()
LR.fit(X_train, y_train)

LinearRegression()

In [14]:
y_pred_lr = LR.predict(X_test)

In [15]:
from sklearn.linear_model import SGDRegressor
SGDR =  SGDRegressor()
SGDR.fit(X_train, y_train)

SGDRegressor()

In [16]:
y_pred_sgdr = SGDR.predict(X_test)
y_pred_sgdr

array([-10037.06304309,  56904.22251112, -24146.55913573, ...,
       313889.89867044, -53997.03146814,  96244.90801786])

In [17]:
from sklearn.linear_model import ElasticNet
EN = ElasticNet()
EN.fit(X_train, y_train)

ElasticNet()

In [18]:
y_pred_en = EN.predict(X_test)
y_pred_en

array([14257.69306499, 65849.62142089,  6048.98285521, ...,
       13794.54793731, 48236.36289019, 59272.70799839])

In [19]:
from sklearn.linear_model import BayesianRidge
BR = BayesianRidge()
BR.fit(X_train, y_train)

BayesianRidge()

In [20]:
y_pred_br = BR.predict(X_test)
y_pred_br

array([ -4191.847665  ,  33666.30025247, -20661.29551538, ...,
       329456.61980701, -26013.83658952, 100828.47926523])

In [21]:
from lightgbm import LGBMRegressor
LGBMR = LGBMRegressor(force_row_wise=True)
LGBMR.fit(X_train, y_train)

[LightGBM] [Info] Total Bins 319
[LightGBM] [Info] Number of data points in the train set: 58443, number of used features: 56
[LightGBM] [Info] Start training from score 26153.147511


LGBMRegressor(force_row_wise=True)

In [22]:
y_pred_lgbmr = LGBMR.predict(X_test)
y_pred_lgbmr

array([ 3.46537749e+03,  3.95522122e+03,  4.40320810e+03, ...,
        1.99106767e+04, -6.23389718e+01,  9.43090967e+04])

In [23]:
from xgboost.sklearn import XGBRegressor
XGBR=XGBRegressor()
XGBR.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [24]:
y_pred_xgbr = XGBR.predict(X_test)
y_pred_xgbr

array([ 2624.0933,  2807.287 ,  5330.664 , ..., 14418.436 , 10653.572 ,
       84753.164 ], dtype=float32)

In [25]:
from catboost import CatBoostRegressor
CBR = CatBoostRegressor()
CBR.fit(X_train, y_train)

Learning rate set to 0.077862
0:	learn: 159705.8478717	total: 145ms	remaining: 2m 24s
1:	learn: 155828.3076962	total: 155ms	remaining: 1m 17s
2:	learn: 152093.5708514	total: 165ms	remaining: 54.8s
3:	learn: 148800.0726094	total: 171ms	remaining: 42.5s
4:	learn: 146058.0897598	total: 177ms	remaining: 35.2s
5:	learn: 143622.5842077	total: 184ms	remaining: 30.4s
6:	learn: 141259.5963330	total: 191ms	remaining: 27.2s
7:	learn: 138445.4992255	total: 199ms	remaining: 24.6s
8:	learn: 135515.7694353	total: 206ms	remaining: 22.7s
9:	learn: 133765.0039107	total: 213ms	remaining: 21.1s
10:	learn: 131011.5994236	total: 221ms	remaining: 19.8s
11:	learn: 128759.9627974	total: 228ms	remaining: 18.7s
12:	learn: 126575.0696186	total: 234ms	remaining: 17.8s
13:	learn: 124801.7876427	total: 241ms	remaining: 17s
14:	learn: 123229.4722050	total: 248ms	remaining: 16.3s
15:	learn: 121874.6404981	total: 255ms	remaining: 15.7s
16:	learn: 120581.5249493	total: 261ms	remaining: 15.1s
17:	learn: 119397.8688787	to

175:	learn: 85739.4504104	total: 1.2s	remaining: 5.6s
176:	learn: 85676.8481843	total: 1.2s	remaining: 5.59s
177:	learn: 85601.0906872	total: 1.21s	remaining: 5.59s
178:	learn: 85505.4451893	total: 1.22s	remaining: 5.58s
179:	learn: 85400.9964384	total: 1.22s	remaining: 5.57s
180:	learn: 85199.1032486	total: 1.23s	remaining: 5.56s
181:	learn: 85138.7748604	total: 1.23s	remaining: 5.55s
182:	learn: 85007.8355236	total: 1.24s	remaining: 5.54s
183:	learn: 84954.7981277	total: 1.25s	remaining: 5.53s
184:	learn: 84897.3993107	total: 1.25s	remaining: 5.51s
185:	learn: 84818.0494348	total: 1.26s	remaining: 5.5s
186:	learn: 84758.9098578	total: 1.26s	remaining: 5.5s
187:	learn: 84699.1190990	total: 1.27s	remaining: 5.48s
188:	learn: 84613.6083387	total: 1.27s	remaining: 5.47s
189:	learn: 84562.2512037	total: 1.28s	remaining: 5.46s
190:	learn: 84454.2073877	total: 1.29s	remaining: 5.45s
191:	learn: 84240.7111124	total: 1.29s	remaining: 5.44s
192:	learn: 84204.9250705	total: 1.3s	remaining: 5.43

347:	learn: 75466.6320278	total: 2.22s	remaining: 4.16s
348:	learn: 75450.4376519	total: 2.23s	remaining: 4.15s
349:	learn: 75427.7765817	total: 2.23s	remaining: 4.14s
350:	learn: 75374.2824687	total: 2.24s	remaining: 4.14s
351:	learn: 75367.7188647	total: 2.24s	remaining: 4.13s
352:	learn: 75363.1935232	total: 2.25s	remaining: 4.12s
353:	learn: 75353.2993566	total: 2.25s	remaining: 4.11s
354:	learn: 75344.4331890	total: 2.26s	remaining: 4.1s
355:	learn: 75343.4912142	total: 2.26s	remaining: 4.1s
356:	learn: 75321.8257149	total: 2.27s	remaining: 4.09s
357:	learn: 75246.7050556	total: 2.28s	remaining: 4.08s
358:	learn: 75168.7753622	total: 2.28s	remaining: 4.08s
359:	learn: 75152.4523606	total: 2.29s	remaining: 4.07s
360:	learn: 75110.9530369	total: 2.29s	remaining: 4.06s
361:	learn: 75077.6253623	total: 2.3s	remaining: 4.05s
362:	learn: 75046.3155772	total: 2.31s	remaining: 4.05s
363:	learn: 75016.8562295	total: 2.31s	remaining: 4.04s
364:	learn: 74988.5200146	total: 2.32s	remaining: 4

521:	learn: 67357.4697316	total: 3.23s	remaining: 2.96s
522:	learn: 67332.5416529	total: 3.24s	remaining: 2.95s
523:	learn: 67322.1618596	total: 3.24s	remaining: 2.95s
524:	learn: 67274.0368155	total: 3.25s	remaining: 2.94s
525:	learn: 67262.6592718	total: 3.25s	remaining: 2.93s
526:	learn: 67251.8576654	total: 3.26s	remaining: 2.93s
527:	learn: 67251.7108789	total: 3.27s	remaining: 2.92s
528:	learn: 67251.5884192	total: 3.27s	remaining: 2.91s
529:	learn: 67212.9186647	total: 3.28s	remaining: 2.91s
530:	learn: 67168.8070605	total: 3.28s	remaining: 2.9s
531:	learn: 67160.8307433	total: 3.29s	remaining: 2.89s
532:	learn: 67124.6993974	total: 3.29s	remaining: 2.89s
533:	learn: 67039.1225278	total: 3.3s	remaining: 2.88s
534:	learn: 67010.7399905	total: 3.31s	remaining: 2.87s
535:	learn: 67010.6129793	total: 3.31s	remaining: 2.87s
536:	learn: 67010.3661264	total: 3.32s	remaining: 2.86s
537:	learn: 66974.1211506	total: 3.32s	remaining: 2.85s
538:	learn: 66974.0038117	total: 3.33s	remaining: 

690:	learn: 59516.8051622	total: 4.23s	remaining: 1.89s
691:	learn: 59489.1007699	total: 4.24s	remaining: 1.89s
692:	learn: 59483.3861302	total: 4.24s	remaining: 1.88s
693:	learn: 59448.7951947	total: 4.25s	remaining: 1.87s
694:	learn: 59441.2121006	total: 4.25s	remaining: 1.87s
695:	learn: 59369.8103166	total: 4.26s	remaining: 1.86s
696:	learn: 59350.3581635	total: 4.27s	remaining: 1.85s
697:	learn: 59284.6936542	total: 4.27s	remaining: 1.85s
698:	learn: 59276.6687995	total: 4.28s	remaining: 1.84s
699:	learn: 59199.3669715	total: 4.28s	remaining: 1.84s
700:	learn: 59180.4312077	total: 4.29s	remaining: 1.83s
701:	learn: 59163.0670639	total: 4.29s	remaining: 1.82s
702:	learn: 59154.0736639	total: 4.3s	remaining: 1.82s
703:	learn: 59115.9351800	total: 4.31s	remaining: 1.81s
704:	learn: 59070.1872293	total: 4.31s	remaining: 1.8s
705:	learn: 59056.3910731	total: 4.32s	remaining: 1.8s
706:	learn: 59031.4128817	total: 4.32s	remaining: 1.79s
707:	learn: 58992.9874413	total: 4.33s	remaining: 1

862:	learn: 54306.5041594	total: 5.25s	remaining: 834ms
863:	learn: 54290.8665066	total: 5.26s	remaining: 828ms
864:	learn: 54267.0126516	total: 5.26s	remaining: 822ms
865:	learn: 54247.9637567	total: 5.27s	remaining: 816ms
866:	learn: 54225.3177036	total: 5.28s	remaining: 810ms
867:	learn: 54204.8011360	total: 5.28s	remaining: 803ms
868:	learn: 54192.1235775	total: 5.29s	remaining: 797ms
869:	learn: 54172.5843795	total: 5.29s	remaining: 791ms
870:	learn: 54160.5614384	total: 5.3s	remaining: 785ms
871:	learn: 54124.4299289	total: 5.31s	remaining: 779ms
872:	learn: 54104.4096489	total: 5.31s	remaining: 773ms
873:	learn: 54093.0002087	total: 5.32s	remaining: 767ms
874:	learn: 54084.3573825	total: 5.32s	remaining: 761ms
875:	learn: 54065.8626213	total: 5.33s	remaining: 754ms
876:	learn: 54046.0020541	total: 5.33s	remaining: 748ms
877:	learn: 54042.5042010	total: 5.34s	remaining: 742ms
878:	learn: 54013.0544252	total: 5.35s	remaining: 736ms
879:	learn: 53997.2960415	total: 5.35s	remaining:

In [26]:
y_pred_cbr = CBR.predict(X_test)
y_pred_cbr

array([ 1403.82900541,  -623.48063023,  4889.98159569, ...,
        5373.05578614, 13327.31042638, 83466.23700511])

In [27]:
# from sklearn.kernel_ridge import KernelRidge
# KR = KernelRidge()
# KR.fit(X_train, y_train)

In [28]:
# y_pred_kr = KR.predict(X_test)

In [29]:
from sklearn.ensemble import RandomForestRegressor
RFR = RandomForestRegressor(n_estimators=500,random_state=42, n_jobs=-1)
RFR.fit(X_train, y_train)

RandomForestRegressor(n_estimators=500, n_jobs=-1, random_state=42)

In [30]:
y_pred_rfr = RFR.predict(X_test)
y_pred_rfr

array([ 3440.45666667,  3440.49238095,  3381.31515873, ...,
        3323.2       ,  3541.4       , 73852.        ])

In [31]:
from sklearn.ensemble import GradientBoostingRegressor
GBR = GradientBoostingRegressor()
GBR.fit(X_train, y_train)

GradientBoostingRegressor()

In [32]:
y_pred_gbr = GBR.predict(X_test)
y_pred_gbr

array([  4523.79431005,  11216.71759209,    171.9168897 , ...,
       170162.69392267,   2615.92347721,  93751.31849907])

In [33]:
from sklearn.svm import SVR
SVR = SVR()
SVR.fit(X_train, y_train)

SVR()

In [34]:
y_pred_svr = SVR.predict(X_test)
y_pred_svr

array([3391.88991237, 3422.89898781, 3321.96779301, ..., 3355.40377481,
       3646.59349134, 4649.22341549])

In [35]:
result_df = pd.DataFrame({
    "y_test":y_test,
    "differ_lr":abs(y_pred_lr-y_test),
    "differ_sgdr":abs(y_pred_sgdr-y_test),
    "differ_en":abs(y_pred_en-y_test),
    "differ_br":abs(y_pred_br-y_test),
    "differ_lgbmr":abs(y_pred_lgbmr-y_test),
    "differ_xgbr":abs(y_pred_xgbr-y_test),
    "differ_cbr":abs(y_pred_cbr-y_test),
#     "differ_kr":abs(y_pred_kr-y_test),
    "differ_rfr":abs(y_pred_rfr-y_test),
    "differ_gbr":abs(y_pred_gbr-y_test),
    "differ_svr":abs(y_pred_svr-y_test),
 })

In [36]:
r_df = result_df.describe(percentiles=[0.5,0.6,0.7,0.8,0.9]).transpose()
rcolumns_l = ['mean', 'std', '50%', '60%', '70%', '80%', '90%']

In [37]:
r_df[rcolumns_l].round(decimals=2)

mean        std       50%       60%       70%       80%  \
y_test        26394.89  164443.98   3400.00   3400.00   3400.00   3500.00   
differ_lr     36450.23  139087.87  15736.40  19685.78  24430.88  31850.90   
differ_sgdr   41827.74  138025.98  21334.85  26635.98  32678.38  41529.78   
differ_en     34117.12  153376.03  15166.81  19922.53  26881.82  36498.14   
differ_br     36454.93  139098.90  15752.28  19703.58  24443.24  31887.78   
differ_lgbmr  15821.50   97093.57    282.60    405.69    800.37   2757.78   
differ_xgbr   14455.82   89574.13    659.06    966.37   1476.19   4706.18   
differ_cbr    15249.85   86448.75   1223.18   1753.14   2936.08   6230.30   
differ_rfr    10827.25   85182.50     41.80     55.13     75.80    166.00   
differ_gbr    20460.52  110784.35   2398.86   3228.08   4581.02  10664.19   
differ_svr    22952.41  164362.30     57.24     77.57     95.80    166.18   

                   90%  
y_test        46000.00  
differ_lr     59656.65  
differ_sgdr   66662.18  
differ_en     54995.83  
differ_br     59657.18  
differ_lgbmr  36513.94  
differ_xgbr   31220.33  
differ_cbr    34079.33  
differ_rfr    15173.40  
differ_gbr    37732.90  
differ_svr    41748.97

In [38]:
result_df.to_excel('../Data/result.xlsx')