In [1]:
import pandas as pd
import numpy as np


In [2]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_excel('./Data/datapro1.xlsx')

In [4]:
# list(df)

In [5]:
cat_columns = [
 '产业链位置',
 '一级技术分支',
 '专利类型',
 '申请人省市代码',
 '专利有效性',
]

In [6]:
ohEncoder = OneHotEncoder(drop='first')
cat_features = ohEncoder.fit_transform(df[cat_columns]).toarray()
cat_features

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 1.]])

In [7]:
num_columns = [ 
 '3年内被引用次数',
 '5年内被引用次数',
 '引用专利数量',
 '被引用专利数量',
 '公开(公告)日',
 '权利要求数量',
 '文献页数',
 '诉讼案件数'
]

In [8]:
stdScaler = StandardScaler()
num_features = stdScaler.fit_transform(df[num_columns])
num_features

array([[-0.35565498, -0.35553307, -0.4584354 , ..., -0.96108065,
        -0.5745365 , -0.01858091],
       [-0.35565498, -0.35553307, -0.4584354 , ..., -0.61086388,
        -1.06995799, -0.01858091],
       [-0.35565498, -0.35553307, -0.4584354 , ...,  1.14021993,
         1.6548602 , -0.01858091],
       ...,
       [-0.35565498, -0.35553307, -0.4584354 , ...,  0.4397864 ,
        -0.5745365 , -0.01858091],
       [-0.35565498, -0.35553307, -0.4584354 , ..., -0.26064712,
        -0.07911501, -0.01858091],
       [-0.35565498, -0.35553307, -0.12499838, ..., -0.26064712,
        -0.32682576, -0.01858091]])

In [9]:
X = np.hstack([cat_features, num_features])
X.shape

(72026, 55)

In [10]:
y = df['专利价值'].to_numpy()
y.shape

(72026,)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3)


In [12]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((57620, 55), (14406, 55), (57620,), (14406,))

In [13]:
from sklearn.linear_model import LinearRegression
LR =  LinearRegression()
LR.fit(X_train, y_train)

LinearRegression()

In [14]:
y_pred_lr = LR.predict(X_test)

In [15]:
from sklearn.linear_model import SGDRegressor
SGDR =  SGDRegressor()
SGDR.fit(X_train, y_train)

SGDRegressor()

In [16]:
y_pred_sgdr = SGDR.predict(X_test)
y_pred_sgdr

array([  2885.2584999 ,   -485.26964767,  12637.48612086, ...,
       127130.40860418,  -9129.76589874,   1594.44537756])

In [17]:
from sklearn.linear_model import ElasticNet
EN = ElasticNet()
EN.fit(X_train, y_train)

ElasticNet()

In [18]:
y_pred_en = EN.predict(X_test)
y_pred_en

array([10533.63192145,  9227.2172808 , 23528.09202746, ...,
       97369.73038716,  1448.83914113,  8912.7893526 ])

In [19]:
from sklearn.linear_model import BayesianRidge
BR = BayesianRidge()
BR.fit(X_train, y_train)

BayesianRidge()

In [20]:
y_pred_br = BR.predict(X_test)
y_pred_br

array([  1328.5262825 ,   -721.15541257,  13570.62954879, ...,
       117691.71981891,  -7582.92650162,   1968.5927481 ])

In [21]:
from lightgbm import LGBMRegressor
LGBMR = LGBMRegressor(force_row_wise=True)
LGBMR.fit(X_train, y_train)

[LightGBM] [Info] Total Bins 297
[LightGBM] [Info] Number of data points in the train set: 57620, number of used features: 53
[LightGBM] [Info] Start training from score 19858.491843


LGBMRegressor(force_row_wise=True)

In [22]:
y_pred_lgbmr = LGBMR.predict(X_test)
y_pred_lgbmr

array([  3653.35119387,   3440.76087534,   4346.79961542, ...,
       122573.50121474,   3440.76087534,   3440.76087534])

In [23]:
from xgboost.sklearn import XGBRegressor
XGBR=XGBRegressor()
XGBR.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [24]:
y_pred_xgbr = XGBR.predict(X_test)
y_pred_xgbr

array([  3282.6956,   3359.2744,   3467.0754, ..., 127409.16  ,
         3203.753 ,   3309.9312], dtype=float32)

In [25]:
from catboost import CatBoostRegressor
CBR = CatBoostRegressor()
CBR.fit(X_train, y_train)

Learning rate set to 0.077687
0:	learn: 101005.5301103	total: 152ms	remaining: 2m 32s
1:	learn: 97128.7105302	total: 156ms	remaining: 1m 18s
2:	learn: 93775.9604492	total: 161ms	remaining: 53.5s
3:	learn: 90680.8160252	total: 165ms	remaining: 41s
4:	learn: 87965.4675645	total: 169ms	remaining: 33.7s
5:	learn: 85528.1594429	total: 174ms	remaining: 28.8s
6:	learn: 83236.9926387	total: 178ms	remaining: 25.3s
7:	learn: 81284.1779623	total: 182ms	remaining: 22.6s
8:	learn: 79515.7185941	total: 186ms	remaining: 20.5s
9:	learn: 77925.3575692	total: 191ms	remaining: 18.9s
10:	learn: 76503.6870370	total: 195ms	remaining: 17.5s
11:	learn: 75238.6219464	total: 201ms	remaining: 16.5s
12:	learn: 74096.3571584	total: 207ms	remaining: 15.7s
13:	learn: 73115.7561469	total: 212ms	remaining: 14.9s
14:	learn: 72229.0868867	total: 218ms	remaining: 14.3s
15:	learn: 71419.6550075	total: 223ms	remaining: 13.7s
16:	learn: 70694.5150483	total: 228ms	remaining: 13.2s
17:	learn: 70014.5718937	total: 233ms	remain

In [26]:
y_pred_cbr = CBR.predict(X_test)
y_pred_cbr

array([  3914.3665095 ,   3217.06461124,   5166.73494647, ...,
       143914.36713986,   3182.20278758,   3684.38135417])

In [27]:
# from sklearn.kernel_ridge import KernelRidge
# KR = KernelRidge()
# KR.fit(X_train, y_train)

In [28]:
# y_pred_kr = KR.predict(X_test)

In [29]:
from sklearn.ensemble import RandomForestRegressor
RFR = RandomForestRegressor(n_estimators=500,random_state=42, n_jobs=-1)
RFR.fit(X_train, y_train)

RandomForestRegressor(n_estimators=500, n_jobs=-1, random_state=42)

In [39]:
RFR.score(X_test,y_test)

0.7668816165737848

In [42]:
from sklearn.model_selection import cross_val_score
# 使用交叉验证评估模型性能
cv_scores = cross_val_score(RFR, X_train, y_train, cv=10, scoring='neg_mean_squared_error')

# 计算均方根误差（Root Mean Squared Error，RMSE）的平均值
rmse_scores = (-cv_scores)**0.5
average_rmse = rmse_scores.mean()

In [43]:
average_rmse

48405.90850277023

In [30]:
y_pred_rfr = RFR.predict(X_test)
y_pred_rfr

array([  3397.1968254 ,   3375.85      ,   3485.65714286, ...,
       138370.        ,   3300.80380952,   3339.01074648])

In [31]:
from sklearn.ensemble import GradientBoostingRegressor
GBR = GradientBoostingRegressor()
GBR.fit(X_train, y_train)

GradientBoostingRegressor()

In [32]:
y_pred_gbr = GBR.predict(X_test)
y_pred_gbr

array([3.13784230e+03, 2.35270663e+03, 1.27322400e+02, ...,
       1.37796906e+05, 2.46184555e+03, 2.35270663e+03])

In [33]:
from sklearn.svm import SVR
SVR = SVR()
SVR.fit(X_train, y_train)

SVR()

In [34]:
y_pred_svr = SVR.predict(X_test)
y_pred_svr

array([3314.85419705, 3312.26350948, 3406.29996826, ..., 4252.67708914,
       3298.63299251, 3302.91172905])

In [35]:
result_df = pd.DataFrame({
    "y_test":y_test,
    "differ_lr":abs(y_pred_lr-y_test),
    "differ_sgdr":abs(y_pred_sgdr-y_test),
    "differ_en":abs(y_pred_en-y_test),
    "differ_br":abs(y_pred_br-y_test),
    "differ_lgbmr":abs(y_pred_lgbmr-y_test),
    "differ_xgbr":abs(y_pred_xgbr-y_test),
    "differ_cbr":abs(y_pred_cbr-y_test),
#     "differ_kr":abs(y_pred_kr-y_test),
    "differ_rfr":abs(y_pred_rfr-y_test),
    "differ_gbr":abs(y_pred_gbr-y_test),
    "differ_svr":abs(y_pred_svr-y_test),
 })

In [36]:
r_df = result_df.describe(percentiles=[0.5,0.6,0.7,0.8,0.9]).transpose()
rcolumns_l = ['mean', 'std', '50%', '60%', '70%', '80%', '90%']

In [37]:
r_df[rcolumns_l].round(decimals=2)

mean       std       50%       60%       70%       80%  \
y_test        20118.05  99430.15   3400.00   3400.00   3400.00   3500.00   
differ_lr     23735.37  85685.45   9567.44  11831.58  14481.34  19130.57   
differ_sgdr   24407.41  85540.25  10367.17  12865.94  15867.04  20390.98   
differ_en     22291.60  92832.18  10184.09  13433.36  17393.51  23139.66   
differ_br     23719.21  85674.33   9575.55  11816.49  14508.78  19147.70   
differ_lgbmr  10777.32  50616.94    175.76    254.88    367.92   1395.27   
differ_xgbr    9554.61  49729.43    280.69    424.98    776.29   3111.60   
differ_cbr    10118.99  43542.23    755.69   1110.34   1811.75   4058.08   
differ_rfr     7468.99  47422.58     40.66     54.50     74.99    143.19   
differ_gbr    13020.44  58553.11    857.92    954.94   1154.11   5915.42   
differ_svr    16681.50  99321.18     54.73     73.28     92.83    139.92   

                   90%  
y_test        41000.00  
differ_lr     42608.89  
differ_sgdr   44008.25  
differ_en     36027.89  
differ_br     42612.32  
differ_lgbmr  28769.40  
differ_xgbr   23692.80  
differ_cbr    26465.29  
differ_rfr    13864.50  
differ_gbr    31937.92  
differ_svr    36568.66

In [42]:
result_df.to_excel('./Data/result.xlsx',index=False)